language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jkulcsar/docker-react-boilerplate -f Dockerfile.dev .

  script:
  - docker run -e CI=true jkulcsar/docker-react-boilerplate npm run test